const DOODLE = {
    UPLOAD: 'DOODLE_UPLOAD',
    UPLOAD_SUCCESS: 'DOODLE_UPLOAD_SUCCESS',
    UPLOAD_ERROR: 'DOODLE_UPLOAD_ERROR',
};

const ACCOUNT = {
    FETCH: 'ACCOUNT_FETCH',
    FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_FETCH_SUCCESSS',
    FETCH_LOGOUT_SUCCESS: 'ACCOUNT_FETCH_LOGOUT_SUCCESS',
    FECTH_AUTHENTICATED_SUCCESS: 'ACCOUNT_FETCH_AUTHENTICATED_SUCCESS'
};

const PUBLIC_DOODLES = {
    FETCH: 'PUBLIC_DOODLES_FETCH',
    FETCH_ERROR: 'PUBLIC_DOODLES_ERROR',
    FETCH_SUCCESS: 'PUBLIC_DOODLES_FETCH_SUCCESS',
    FETCH_DELETE_SUCCESS: 'PUBLIC_DOODLES_FETCH_DELETE_SUCCESS',
    CURRENT: 'PUBLIC_DOODLES_CURRENT',
};

export { DOODLE, ACCOUNT, PUBLIC_DOODLES };