const DOODLE = {
    UPLOAD: 'DOODLE_UPLOAD',
    UPLOAD_SUCCESS: 'DOODLE_UPLOAD_SUCCESS',
    UPLOAD_ERROR: 'DOODLE_UPLOAD_ERROR'   
};

const ACCOUNT = {
    FETCH: 'ACCOUNT_FETCH',
    FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_FETCH_SUCCESSS',
    FETCH_LOGOUT_SUCCESS: 'ACCOUNT_FETCH_LOGOUT_SUCCESS',
    FECTH_AUTHENTICATED_SUCCESS: 'ACCOUNT_FETCH_AUTHENTICATED_SUCCESS'
};


export { DOODLE, ACCOUNT };